// typegen — generate the frontend's eventproto.generated.ts from the Go
// source-of-truth (mini-world/eventproto/categories.go) plus
// optionally the relay's synthetic-event source (when present).
//
// Usage:
//   go run mini-world/cmd/typegen <output_path>
//
// Or via the go:generate directive in mini-world/eventproto/gen.go.
//
// Implementation is deliberately small and stdlib-only. We walk the AST of
// `internal/eventproto/categories.go`, extract every `Category*` string
// constant, and emit a TypeScript file containing:
//   - WORLDSIM_CATEGORIES const tuple in declaration order
//   - WorldsimCategory string-literal union from that tuple
//   - RELAY_SYNTHETIC_CATEGORIES const tuple (hand-coded list mirroring
//     crossworlds-relay/enrich.go for now; will swap to AST-walk of the
//     relay's eventproto package when that package exists)
//   - RelaySyntheticCategory string-literal union
//   - EventCategory union of the two above
//
// The TypeScript output is committed to git so the frontend has no Go
// build dependency. Re-running on identical input produces identical
// output (deterministic).

package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
)

// relaySyntheticCategories are the categories the relay emits itself
// (not via worldsim). Source of truth is `crossworlds-relay/enrich.go`.
// Hand-maintained here for v0; future work could AST-walk a parallel
// eventproto package in the relay repo.
var relaySyntheticCategories = []string{
	"baby_boom",
	"crime_wave",
	"trade_burst",
	"regime_change",
	"activity",
}

func main() {
	if len(os.Args) != 2 {
		fmt.Fprintln(os.Stderr, "usage: typegen <output_path>")
		os.Exit(2)
	}
	outPath := os.Args[1]

	// Resolve the Go source. We're called via go:generate from the eventproto
	// package directory, so the source file is in the working directory.
	// When called manually with an absolute path, fall back to a known
	// relative location.
	srcPath := "categories.go"
	if _, err := os.Stat(srcPath); err != nil {
		srcPath = "internal/eventproto/categories.go"
	}

	worldCats, err := extractCategoryConstants(srcPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "extract worldsim categories: %v\n", err)
		os.Exit(1)
	}
	if len(worldCats) == 0 {
		fmt.Fprintln(os.Stderr, "no Category* constants found — refusing to emit empty file")
		os.Exit(1)
	}

	out := renderTypeScript(worldCats, relaySyntheticCategories)

	// Ensure parent dir exists, then write atomically.
	if err := os.MkdirAll(filepath.Dir(outPath), 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "mkdir: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(outPath, []byte(out), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write %s: %v\n", outPath, err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "typegen: wrote %d worldsim + %d relay categories → %s\n",
		len(worldCats), len(relaySyntheticCategories), outPath)
}

// extractCategoryConstants parses the Go file and returns the string values
// of every `Category*` typed constant in declaration order.
func extractCategoryConstants(srcPath string) ([]string, error) {
	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, srcPath, nil, parser.ParseComments)
	if err != nil {
		return nil, fmt.Errorf("parse %s: %w", srcPath, err)
	}

	var cats []string
	for _, decl := range node.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok || gen.Tok != token.CONST {
			continue
		}
		for _, spec := range gen.Specs {
			vs, ok := spec.(*ast.ValueSpec)
			if !ok {
				continue
			}
			// Each ValueSpec is one line like:
			//   CategoryDeath Category = "death"
			// Filter to ones whose names start with "Category".
			for i, name := range vs.Names {
				if !strings.HasPrefix(name.Name, "Category") {
					continue
				}
				if i >= len(vs.Values) {
					continue
				}
				lit, ok := vs.Values[i].(*ast.BasicLit)
				if !ok || lit.Kind != token.STRING {
					continue
				}
				// lit.Value includes the surrounding quotes.
				cats = append(cats, strings.Trim(lit.Value, `"`))
			}
		}
	}
	return cats, nil
}

// renderTypeScript builds the output file. Pure string concatenation —
// no template engine — to keep the dependency surface zero.
func renderTypeScript(worldCats, relayCats []string) string {
	var b bytes.Buffer

	b.WriteString("// AUTO-GENERATED by mini-world/cmd/typegen — DO NOT EDIT BY HAND.\n")
	b.WriteString("// Source of truth: mini-world/eventproto/categories.go\n")
	b.WriteString("// Run `go generate ./...` from mini-world/ to regenerate.\n")
	b.WriteString("//\n")
	b.WriteString("// Schema sharing eliminates the three-place coupling between worldsim\n")
	b.WriteString("// event emit, relay allowlist, and frontend SSE handlers (R84,\n")
	b.WriteString("// Phase 5.2). See `docs/23-schema-sharing-design.md`.\n")
	b.WriteString("\n")

	// Worldsim categories
	b.WriteString("export const WORLDSIM_CATEGORIES = [\n")
	for _, c := range worldCats {
		fmt.Fprintf(&b, "\t'%s',\n", c)
	}
	b.WriteString("] as const;\n")
	b.WriteString("export type WorldsimCategory = typeof WORLDSIM_CATEGORIES[number];\n\n")

	// Relay synthetic categories
	b.WriteString("export const RELAY_SYNTHETIC_CATEGORIES = [\n")
	for _, c := range relayCats {
		fmt.Fprintf(&b, "\t'%s',\n", c)
	}
	b.WriteString("] as const;\n")
	b.WriteString("export type RelaySyntheticCategory = typeof RELAY_SYNTHETIC_CATEGORIES[number];\n\n")

	// Combined union
	b.WriteString("/** Every category the SSE stream may carry. */\n")
	b.WriteString("export type EventCategory = WorldsimCategory | RelaySyntheticCategory;\n\n")

	// Helper sets for runtime checks (since the const tuples are read-only).
	b.WriteString("/** Runtime helper: is this an event the worldsim itself emitted? */\n")
	b.WriteString("export function isWorldsimCategory(c: string): c is WorldsimCategory {\n")
	b.WriteString("\treturn (WORLDSIM_CATEGORIES as readonly string[]).includes(c);\n")
	b.WriteString("}\n\n")
	b.WriteString("/** Runtime helper: is this a relay-emitted synthetic event? */\n")
	b.WriteString("export function isRelaySyntheticCategory(c: string): c is RelaySyntheticCategory {\n")
	b.WriteString("\treturn (RELAY_SYNTHETIC_CATEGORIES as readonly string[]).includes(c);\n")
	b.WriteString("}\n")

	return b.String()
}
